apiVersion: v1
kind: Service
metadata:
  name: xmrig-proxy
  namespace: xmrig-proxy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3333
      targetPort: http
  selector:
    app: xmrig-proxy
  type: LoadBalancer
