apiVersion: v1
kind: ConfigMap
metadata:
  name: xmrig-proxy-configmap
  namespace: xmrig-proxy
data:
  config.json: |
    {
      "access-log-file": null,
      "access-password": null,
      "algo-ext": true,
      "api": {
          "id": null,
          "worker-id": null
      },
      "http": {
          "enabled": false,
          "host": "127.0.0.1",
          "port": 0,
          "access-token": null,
          "restricted": true
      },
      "background": false,
      "bind": [
          {
              "host": "0.0.0.0",
              "port": 3333,
              "tls": false
          },
          {
              "host": "::",
              "port": 3333,
              "tls": false
          }
      ],
      "colors": true,
      "title": true,
      "custom-diff": 1000000,
      "custom-diff-stats": true,
      "donate-level": 1,
      "log-file": null,
      "mode": "simple",
      "pools": [
          {
              "algo": null,
              "coin": "monero",
              "url": "",
              "user": "x+600000",
              "pass": "x",
              "rig-id": null,
              "keepalive": true,
              "enabled": true,
              "tls": false,
              "tls-fingerprint": null,
              "daemon": false,
        "nicehash": false
          }
      ],
      "retries": 2,
      "retry-pause": 1,
      "reuse-timeout": 0,
      "tls": {
          "enabled": true,
          "protocols": null,
          "cert": null,
          "cert_key": null,
          "ciphers": null,
          "ciphersuites": null,
          "dhparam": null
      },
      "user-agent": null,
      "syslog": false,
      "verbose": false,
      "watch": true,
      "workers": true
    }
